import { useEffect, useState } from 'react'
import { getCatalog, explainMatch, sendFeedback } from '../api'
import ExplainPanel from '../components/ExplainPanel'
import PageHeader from '../components/PageHeader'
import ScoreBadge from '../components/ScoreBadge'
export default function Review(){
 const [rows,setRows]=useState([]); const [explanation,setExplanation]=useState(null); const [filter,setFilter]=useState('clusters'); const [loading,setLoading]=useState(true)
 useEffect(()=>{getCatalog(300,0).then(r=>setRows(r.data.rows)).catch(()=>{}).finally(()=>setLoading(false))},[])
 const grouped=rows.reduce((a,r)=>{(a[r.national_code] ||= []).push(r);return a},{})
 const clusters=Object.entries(grouped).filter(([,v])=>v.length>1)
 const open=async(a,b)=>{const ia=rows.findIndex(r=>`${r.cpse_id}-${r.source_code}`===a),ib=rows.findIndex(r=>`${r.cpse_id}-${r.source_code}`===b); if(ia>=0&&ib>=0) setExplanation((await explainMatch(ia,ib)).data)}
 const act=async(action,it,nc)=>{await sendFeedback({national_code:nc,cpse_id:it.cpse_id,source_code:it.source_code,action}); alert(`${action} logged for ${it.source_code}`)}
 return <div><PageHeader eyebrow="GOVERNANCE" title="Duplicate review" description="Human-in-the-loop workspace for validating AI-suggested material harmonization." action={<div className="filter-pills">{['clusters','high','reviewed'].map(x=><button className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x==='clusters'?'All clusters':x==='high'?'High confidence':'Reviewed'}</button>)}</div>}/>{loading?<div className="panel loading-state">Loading catalog…</div>:<div className="review-layout"><div className="cluster-list">{clusters.slice(0,30).map(([nc,items],idx)=><section className="panel cluster-card" key={nc}><div className="cluster-head"><div><span className="cluster-index">CLUSTER {String(idx+1).padStart(3,'0')}</span><strong>{nc}</strong></div><ScoreBadge score={Math.min(.98,.72+items.length*.05)} decision={items.length>2?'REVIEW':'AUTO'}/></div><div className="cluster-table"><div className="cluster-table-head"><span>CPSE / SOURCE</span><span>DESCRIPTION</span><span>ACTION</span></div>{items.map((it,i)=><div className="cluster-line" key={i}><div><strong>{it.cpse_id}</strong><span>{it.source_code}</span></div><div>{it.raw_description}</div><div className="action-stack"><button className="link-btn approve" onClick={()=>act('APPROVE',it,nc)}>Approve</button><button className="link-btn reject" onClick={()=>act('REJECT',it,nc)}>Reject</button>{i>0&&<button className="link-btn explain" onClick={()=>open(`${items[0].cpse_id}-${items[0].source_code}`,`${it.cpse_id}-${it.source_code}`)}>Explain</button>}</div></div>)}</div></section>)}</div><div className="explain-sticky">{explanation?<ExplainPanel data={explanation}/>:<section className="panel empty-explain"><div className="empty-icon">AI</div><h3>Select a pair to explain</h3><p>Click <b>Explain</b> on any duplicate cluster to inspect semantic and attribute-level evidence.</p></section>}</div></div>}</div>
}
